[2024-01-22 21:08:24,349] INFO [GroupCoordinator 0]: Member[group.instance.id None, member.id connect-1-e93a1047-5f47-4700-8e87-94844f1846bf] in group connect-cluster has left, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2024-01-22 21:08:24,350] INFO [GroupCoordinator 0]: Preparing to rebalance group connect-cluster in state PreparingRebalance with old generation 1 (__consumer_offsets-13) (reason: removing member connect-1-e93a1047-5f47-4700-8e87-94844f1846bf on LeaveGroup) (kafka.coordinator.group.GroupCoordinator)
[2024-01-22 21:08:24,351] INFO [GroupCoordinator 0]: Group connect-cluster with generation 2 is now empty (__consumer_offsets-13) (kafka.coordinator.group.GroupCoordinator)
[2024-01-22 21:08:39,840] INFO [GroupMetadataManager brokerId=0] Group connect-cluster transitioned to Dead in generation 2 (kafka.coordinator.group.GroupMetadataManager)
[2024-01-22 21:44:00,784] INFO [GroupCoordinator 0]: Preparing to rebalance group connect-cluster in state PreparingRebalance with old generation 0 (__consumer_offsets-13) (reason: Adding new member connect-1-8467a9f4-4954-483f-8c1d-5acfb5f8dc62 with group instance id None) (kafka.coordinator.group.GroupCoordinator)
[2024-01-22 21:44:00,785] INFO [GroupCoordinator 0]: Stabilized group connect-cluster generation 1 (__consumer_offsets-13) (kafka.coordinator.group.GroupCoordinator)
[2024-01-22 21:44:00,789] INFO [GroupCoordinator 0]: Assignment received from leader for group connect-cluster for generation 1 (kafka.coordinator.group.GroupCoordinator)
[2024-01-22 21:50:23,373] INFO [GroupCoordinator 0]: Member[group.instance.id None, member.id connect-1-8467a9f4-4954-483f-8c1d-5acfb5f8dc62] in group connect-cluster has left, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2024-01-22 21:50:23,374] INFO [GroupCoordinator 0]: Preparing to rebalance group connect-cluster in state PreparingRebalance with old generation 1 (__consumer_offsets-13) (reason: removing member connect-1-8467a9f4-4954-483f-8c1d-5acfb5f8dc62 on LeaveGroup) (kafka.coordinator.group.GroupCoordinator)
[2024-01-22 21:50:23,374] INFO [GroupCoordinator 0]: Group connect-cluster with generation 2 is now empty (__consumer_offsets-13) (kafka.coordinator.group.GroupCoordinator)
[2024-01-22 21:57:27,715] INFO [GroupCoordinator 0]: Preparing to rebalance group connect-cluster in state PreparingRebalance with old generation 2 (__consumer_offsets-13) (reason: Adding new member connect-1-fda05877-d756-4490-9d8a-18e6ec4bdd68 with group instance id None) (kafka.coordinator.group.GroupCoordinator)
[2024-01-22 21:57:27,716] INFO [GroupCoordinator 0]: Stabilized group connect-cluster generation 3 (__consumer_offsets-13) (kafka.coordinator.group.GroupCoordinator)
[2024-01-22 21:57:27,726] INFO [GroupCoordinator 0]: Assignment received from leader for group connect-cluster for generation 3 (kafka.coordinator.group.GroupCoordinator)
[2024-01-22 21:59:06,868] INFO Unable to read additional data from server sessionid 0x10000531bdd0000, likely server has closed socket, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
[2024-01-22 21:59:08,133] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2024-01-22 21:59:08,136] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2024-01-22 21:59:09,088] INFO [GroupCoordinator 0]: Member[group.instance.id None, member.id connect-1-fda05877-d756-4490-9d8a-18e6ec4bdd68] in group connect-cluster has left, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2024-01-22 21:59:09,088] INFO [GroupCoordinator 0]: Preparing to rebalance group connect-cluster in state PreparingRebalance with old generation 3 (__consumer_offsets-13) (reason: removing member connect-1-fda05877-d756-4490-9d8a-18e6ec4bdd68 on LeaveGroup) (kafka.coordinator.group.GroupCoordinator)
[2024-01-22 21:59:09,089] INFO [GroupCoordinator 0]: Group connect-cluster with generation 4 is now empty (__consumer_offsets-13) (kafka.coordinator.group.GroupCoordinator)
[2024-01-22 21:59:09,643] INFO Opening socket connection to server localhost/[0:0:0:0:0:0:0:1]:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2024-01-22 21:59:09,645] INFO Socket error occurred: localhost/[0:0:0:0:0:0:0:1]:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2024-01-22 21:59:11,476] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2024-01-22 21:59:11,477] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2024-01-22 21:59:11,626] INFO Terminating process due to signal SIGINT (org.apache.kafka.common.utils.LoggingSignalHandler)
[2024-01-22 21:59:11,629] INFO [KafkaServer id=0] shutting down (kafka.server.KafkaServer)
[2024-01-22 21:59:11,630] INFO [KafkaServer id=0] Starting controlled shutdown (kafka.server.KafkaServer)
[2024-01-22 21:59:13,386] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2024-01-22 21:59:13,387] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2024-01-22 21:59:13,494] INFO [ZooKeeperClient Kafka server] Waiting until connected. (kafka.zookeeper.ZooKeeperClient)
[2024-01-22 21:59:15,491] INFO Opening socket connection to server localhost/[0:0:0:0:0:0:0:1]:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2024-01-22 21:59:15,496] INFO Socket error occurred: localhost/[0:0:0:0:0:0:0:1]:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2024-01-22 21:59:17,142] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2024-01-22 21:59:17,143] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2024-01-22 21:59:19,108] INFO Opening socket connection to server localhost/[0:0:0:0:0:0:0:1]:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2024-01-22 21:59:19,109] INFO Socket error occurred: localhost/[0:0:0:0:0:0:0:1]:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2024-01-22 21:59:20,547] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2024-01-22 21:59:20,548] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2024-01-22 21:59:22,315] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2024-01-22 21:59:22,316] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2024-01-22 21:59:23,635] INFO Opening socket connection to server localhost/[0:0:0:0:0:0:0:1]:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2024-01-22 21:59:23,637] INFO Socket error occurred: localhost/[0:0:0:0:0:0:0:1]:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2024-01-22 21:59:24,645] INFO [GroupCoordinator 0]: Member[group.instance.id None, member.id consumer-console-consumer-38328-1-047e6011-b034-48f4-a2a2-9774e52dbbfe] in group console-consumer-38328 has left, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2024-01-22 21:59:24,645] INFO [GroupCoordinator 0]: Preparing to rebalance group console-consumer-38328 in state PreparingRebalance with old generation 1 (__consumer_offsets-35) (reason: removing member consumer-console-consumer-38328-1-047e6011-b034-48f4-a2a2-9774e52dbbfe on LeaveGroup) (kafka.coordinator.group.GroupCoordinator)
[2024-01-22 21:59:24,646] INFO [GroupCoordinator 0]: Group console-consumer-38328 with generation 2 is now empty (__consumer_offsets-35) (kafka.coordinator.group.GroupCoordinator)
[2024-01-22 21:59:24,959] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2024-01-22 21:59:24,960] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2024-01-22 21:59:26,148] INFO Opening socket connection to server localhost/[0:0:0:0:0:0:0:1]:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2024-01-22 21:59:26,149] INFO Socket error occurred: localhost/[0:0:0:0:0:0:0:1]:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2024-01-22 21:59:28,082] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2024-01-22 21:59:28,083] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2024-01-22 21:59:30,157] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2024-01-22 21:59:30,159] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2024-01-22 21:59:31,506] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2024-01-22 21:59:31,507] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2024-01-22 21:59:32,865] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2024-01-22 21:59:32,867] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2024-01-22 21:59:34,415] INFO Opening socket connection to server localhost/[0:0:0:0:0:0:0:1]:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2024-01-22 21:59:34,417] INFO Socket error occurred: localhost/[0:0:0:0:0:0:0:1]:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2024-01-22 21:59:36,306] INFO Opening socket connection to server localhost/[0:0:0:0:0:0:0:1]:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2024-01-22 21:59:36,307] INFO Socket error occurred: localhost/[0:0:0:0:0:0:0:1]:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2024-01-22 21:59:38,273] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2024-01-22 21:59:38,274] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2024-01-22 21:59:40,052] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2024-01-22 21:59:40,053] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
